export const skiPackagesData = [
    {
      title: "Gulmarg Beginner Ski Course",
      image: "/images/packages/skiing.jpg",
      location: "Gulmarg",
      duration: "2 days",
      people: "Per Person",
      price: "₹7,999",
    },
    {
      title: "Gulmarg Intermediate Ski Course",
      image: "/images/packages/skiing.jpg",
      location: "Gulmarg",
      duration: "3 days",
      people: "Per Person",
      price: "₹11,500",
    },
    {
      title: "Gulmarg Advanced Ski Course",
      image: "/images/packages/skiing.jpg",
      location: "Gulmarg",
      duration: "4 days",
      people: "Per Person",
      price: "₹16,000",
    },
    {
      title: "Gulmarg Ski and Snowboarding Combo",
      image: "/images/packages/snowboarding.jpg",
      location: "Gulmarg",
      duration: "5 days",
      people: "Per Person",
      price: "₹18,500",
    },
    {
      title: "Gulmarg Private Ski Lessons",
      image: "/images/packages/skiing.jpg",
      location: "Gulmarg",
      duration: "2 days",
      people: "Per Person",
      price: "₹12,000",
    },
    {
      title: "Gulmarg Kids Ski Camp",
      image: "/images/packages/skiing.jpg",
      location: "Gulmarg",
      duration: "3 days",
      people: "Per Person",
      price: "₹9,500",
    },
    {
      title: "Gulmarg Snow Adventure Weekend",
      image: "/images/packages/ski_snow_adventure.jpg",
      location: "Gulmarg",
      duration: "3 days",
      people: "Per Person",
      price: "₹10,999",
    },
  ];
  